// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using core.Contexts;

#nullable disable

namespace core.Migrations
{
    [DbContext(typeof(SigmonDbContext))]
    [Migration("20241031180353_LoreMigration")]
    partial class LoreMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("core.Models.Bill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly?>("ExpiralDate")
                        .HasColumnType("date")
                        .HasColumnName("expiral_date");

                    b.Property<DateOnly?>("PaymentDate")
                        .HasColumnType("date")
                        .HasColumnName("payment_date");

                    b.Property<decimal>("PaymentDue")
                        .HasColumnType("decimal(5, 4)")
                        .HasColumnName("payment_due");

                    b.Property<Guid?>("SubscriptionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SubscriptionId");

                    b.ToTable("Bills");
                });

            modelBuilder.Entity("core.Models.Country", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<string>("PhoneCode")
                        .HasColumnType("varchar(3)")
                        .HasColumnName("phone_code");

                    b.HasKey("Id");

                    b.HasIndex("PhoneCode")
                        .IsUnique()
                        .HasFilter("[phone_code] IS NOT NULL");

                    b.ToTable("Country");
                });

            modelBuilder.Entity("core.Models.Subscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("PaymentDue")
                        .HasColumnType("decimal(5, 4)")
                        .HasColumnName("payment_due");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("tierId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.HasIndex("tierId");

                    b.ToTable("Subscriptions");
                });

            modelBuilder.Entity("core.Models.Tier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("BasePricing")
                        .HasColumnType("decimal(5, 4)")
                        .HasColumnName("base_pricing");

                    b.Property<string>("ModelDescription")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("model_desctiption");

                    b.Property<byte>("ModelNumber")
                        .HasColumnType("tinyint")
                        .HasColumnName("model_number");

                    b.HasKey("Id");

                    b.ToTable("Tier");
                });

            modelBuilder.Entity("core.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("varchar(17)")
                        .HasColumnName("phone");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("core.Models.Bill", b =>
                {
                    b.HasOne("core.Models.Subscription", "Subscription")
                        .WithMany("Bills")
                        .HasForeignKey("SubscriptionId");

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("core.Models.Subscription", b =>
                {
                    b.HasOne("core.Models.User", "User")
                        .WithOne("Subscription")
                        .HasForeignKey("core.Models.Subscription", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("core.Models.Tier", "tier")
                        .WithMany()
                        .HasForeignKey("tierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("tier");
                });

            modelBuilder.Entity("core.Models.Subscription", b =>
                {
                    b.Navigation("Bills");
                });

            modelBuilder.Entity("core.Models.User", b =>
                {
                    b.Navigation("Subscription");
                });
#pragma warning restore 612, 618
        }
    }
}
